# BASIC STATISTICS-2

Problem Statement : Hospital Patient Data Analysis

1.	Load the patient dataset and show summary with info().

In [1]:
import pandas as pd

patient_df = pd.read_csv("Patient_Data.csv")
billing_df = pd.read_csv("Billing_Data.csv")

patient_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   PatientID       6 non-null      int64
 1   Name            6 non-null      object
 2   Department      6 non-null      object
 3   Doctor          6 non-null      object
 4   BillAmount      4 non-null      float64
 5   ReceptionistID  6 non-null      int64
 6   CheckInTime     6 non-null      object
dtypes: float64(1), int64(2), object(4)
memory usage: 468.0+ bytes

2.	Select only the columns relevant for billing: ['PatientID', 'Department', 'Doctor', 'BillAmount'].

In [2]:
billing_columns = patient_df[['PatientID', 'Department', 'Doctor', 'BillAmount']]
print(billing_columns.head())

   PatientID   Department     Doctor  BillAmount
0        101   Cardiology  Dr. Smith      5000.0
1        102    Neurology   Dr. John         NaN
2        103  Orthopedics    Dr. Lee      7500.0
3        104   Cardiology  Dr. Smith      6200.0
4        105  Dermatology   Dr. Rose         NaN

3.	Drop administrative columns like ['ReceptionistID', 'CheckInTime'].

In [4]:
patient_df = patient_df.drop(columns=['ReceptionistID', 'CheckInTime'], errors='ignore')
patient_df

   PatientID     Name   Department     Doctor  BillAmount
0        101    Alice   Cardiology  Dr. Smith      5000.0
1        102      Bob    Neurology   Dr. John         NaN
2        103  Charlie  Orthopedics    Dr. Lee      7500.0
3        104    David   Cardiology  Dr. Smith      6200.0
4        105      Eva  Dermatology   Dr. Rose         NaN
5        101    Alice   Cardiology  Dr. Smith      5000.0

4.	Use groupby to find total bill amount per department.

In [5]:
dept_bill = patient_df.groupby('Department')['BillAmount'].sum()

print(dept_bill)

Department
Cardiology     16200.0
Dermatology        0.0
Neurology          0.0
Orthopedics     7500.0
Name: BillAmount, dtype: float64

5.	Remove duplicate patient records based on PatientID.

In [7]:
patient_df = patient_df.drop_duplicates(subset='PatientID')
patient_df

   PatientID     Name   Department     Doctor  BillAmount
0        101    Alice   Cardiology  Dr. Smith      5000.0
1        102      Bob    Neurology   Dr. John         NaN
2        103  Charlie  Orthopedics    Dr. Lee      7500.0
3        104    David   Cardiology  Dr. Smith      6200.0
4        105      Eva  Dermatology   Dr. Rose         NaN

6.	Fill missing BillAmount values with the mean bill amount.

In [10]:
mean_bill = patient_df['BillAmount'].mean()

patient_df['BillAmount'] = patient_df['BillAmount'].fillna(mean_bill)
patient_df

   PatientID     Name   Department     Doctor   BillAmount
0        101    Alice   Cardiology  Dr. Smith  5000.000000
1        102      Bob    Neurology   Dr. John  6233.333333
2        103  Charlie  Orthopedics    Dr. Lee  7500.000000
3        104    David   Cardiology  Dr. Smith  6200.000000
4        105      Eva  Dermatology   Dr. Rose  6233.333333

7.	Merge the billing dataset with patient dataset on PatientID.

In [11]:
merged_df = pd.merge(patient_df, billing_df, on='PatientID', how='inner')

print(merged_df.head())

   PatientID     Name   Department     Doctor   BillAmount  InsuranceCovered  \
0        101    Alice   Cardiology  Dr. Smith  5000.000000              2000
1        102      Bob    Neurology   Dr. John  6233.333333              1500
2        103  Charlie  Orthopedics    Dr. Lee  7500.000000              2500
3        104    David   Cardiology  Dr. Smith  6200.000000              3000
4        105      Eva  Dermatology   Dr. Rose  6233.333333              1000

   FinalAmount
0         3000
1         3500
2         5000
3         3200
4         4000

8.	Concatenate an additional DataFrame that contains new patients for the current week (row-wise).

In [13]:
new_patients = pd.DataFrame({
    'PatientID': [201,202],
    'Department': ['Cardiology','Neurology'],
    'Doctor': ['Dr.A','Dr.B'],
    'BillAmount': [5000,7000]
})

patient_df = pd.concat([patient_df, new_patients], axis=0, ignore_index=True)
patient_df

   PatientID     Name   Department     Doctor   BillAmount
0        101    Alice   Cardiology  Dr. Smith  5000.000000
1        102      Bob    Neurology   Dr. John  6233.333333
2        103  Charlie  Orthopedics    Dr. Lee  7500.000000
3        104    David   Cardiology  Dr. Smith  6200.000000
4        105      Eva  Dermatology   Dr. Rose  6233.333333
5        201      NaN   Cardiology       Dr.A  5000.000000
6        202      NaN    Neurology       Dr.B  7000.000000
7        201      NaN   Cardiology       Dr.A  5000.000000
8        202      NaN    Neurology       Dr.B  7000.000000

9.	Concatenate new billing category columns like ['InsuranceCovered', 'FinalAmount'] (column-wise).

In [15]:
new_columns = pd.DataFrame({
    'InsuranceCovered': ['Yes','No','Yes'],
    'FinalAmount': [4000,6500,5500]
})

patient_df = pd.concat([patient_df, new_columns], axis=1)
patient_df

,PatientID,Name,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.000000,Yes,4000.0,Yes,4000.0
1,102,Bob,Neurology,Dr. John,6233.333333,No,6500.0,No,6500.0
2,103,Charlie,Orthopedics,Dr. Lee,7500.000000,Yes,5500.0,Yes,5500.0
3,104,David,Cardiology,Dr. Smith,6200.000000,NaN,NaN,NaN,NaN
4,105,Eva,Dermatology,Dr. Rose,6233.333333,NaN,NaN,NaN,NaN
5,201,NaN,Cardiology,Dr.A,5000.000000,NaN,NaN,NaN,NaN
6,202,NaN,Neurology,Dr.B,7000.000000,NaN,NaN,NaN,NaN
7,201,NaN,Cardiology,Dr.A,5000.000000,NaN,NaN,NaN,NaN
8,202,NaN,Neurology,Dr.B,7000.000000,NaN,NaN,NaN,NaN

In [17]:
print(patient_df.head())

   PatientID     Name   Department     Doctor   BillAmount InsuranceCovered  \
0        101    Alice   Cardiology  Dr. Smith  5000.000000              Yes
1        102      Bob    Neurology   Dr. John  6233.333333               No
2        103  Charlie  Orthopedics    Dr. Lee  7500.000000              Yes
3        104    David   Cardiology  Dr. Smith  6200.000000              NaN
4        105      Eva  Dermatology   Dr. Rose  6233.333333              NaN

   FinalAmount InsuranceCovered  FinalAmount
0       4000.0              Yes       4000.0
1       6500.0               No       6500.0
2       5500.0              Yes       5500.0
3          NaN              NaN          NaN
4          NaN              NaN          NaN

In [18]:
print(patient_df.isnull().sum())

PatientID           0
Name                4
Department          0
Doctor              0
BillAmount          0
InsuranceCovered    6
FinalAmount         6
InsuranceCovered    6
FinalAmount         6
dtype: int64