# DATA PREPROCESSING AND FEATURE ENGINEERING IN MACHINE LEARNING

1.	Handle missing values as per the best practices (imputation, removal, etc.).

In [2]:
import pandas as pd
import numpy as np

# Load dataset
df = pd.read_csv("adult_with_headers (1).csv")

# Display first rows
df.head()

# Dataset information
df.info()

# Summary statistics
df.describe()

# Check missing values
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  int64
 1   workclass       32561 non-null  object
 2   fnlwgt          32561 non-null  int64
 3   education       32561 non-null  object
 4   education_num   32561 non-null  int64
 5   marital_status  32561 non-null  object
 6   occupation      32561 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital_gain    32561 non-null  int64
 11  capital_loss    32561 non-null  int64
 12  hours_per_week  32561 non-null  int64
 13  native_country  32561 non-null  object
 14  income          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB

age               0
workclass         0
fnlwgt            0
education         0
education_num     0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
income            0
dtype: int64

●	Apply scaling techniques to numerical features:
a.	Standard Scaling   b. Min-Max Scaling

In [3]:
### a.Standard Scaling
from sklearn.preprocessing import StandardScaler
import pandas as pd

# Select numerical columns
num_cols = df.select_dtypes(include=['int64','float64']).columns

# Apply Standard Scaling
scaler = StandardScaler()
df_standard_scaled = df.copy()

df_standard_scaled[num_cols] = scaler.fit_transform(df_standard_scaled[num_cols])

df_standard_scaled.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,0.030671,State-gov,-1.063611,Bachelors,1.134739,Never-married,Adm-clerical,Not-in-family,White,Male,0.148453,-0.21666,-0.035429,United-States,<=50K
1,0.837109,Self-emp-not-inc,-1.008707,Bachelors,1.134739,Married-civ-spouse,Exec-managerial,Husband,White,Male,-0.145920,-0.21666,-2.222153,United-States,<=50K
2,-0.042642,Private,0.245079,HS-grad,-0.420060,Divorced,Handlers-cleaners,Not-in-family,White,Male,-0.145920,-0.21666,-0.035429,United-States,<=50K
3,1.057047,Private,0.425801,11th,-1.197459,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,-0.145920,-0.21666,-0.035429,United-States,<=50K
4,-0.775768,Private,1.408176,Bachelors,1.134739,Married-civ-spouse,Prof-specialty,Wife,Black,Female,-0.145920,-0.21666,-0.035429,Cuba,<=50K

In [4]:
###  b. Min-Max Scaling
from sklearn.preprocessing import MinMaxScaler

# Apply Min-Max Scaling
scaler = MinMaxScaler()

df_minmax_scaled = df.copy()

df_minmax_scaled[num_cols] = scaler.fit_transform(df_minmax_scaled[num_cols])

df_minmax_scaled.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,0.301370,State-gov,0.044302,Bachelors,0.800000,Never-married,Adm-clerical,Not-in-family,White,Male,0.02174,0.0,0.397959,United-States,<=50K
1,0.452055,Self-emp-not-inc,0.048238,Bachelors,0.800000,Married-civ-spouse,Exec-managerial,Husband,White,Male,0.00000,0.0,0.122449,United-States,<=50K
2,0.287671,Private,0.138113,HS-grad,0.533333,Divorced,Handlers-cleaners,Not-in-family,White,Male,0.00000,0.0,0.397959,United-States,<=50K
3,0.493151,Private,0.151068,11th,0.400000,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0.00000,0.0,0.397959,United-States,<=50K
4,0.150685,Private,0.221488,Bachelors,0.800000,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0.00000,0.0,0.397959,Cuba,<=50K

●	Discuss the scenarios where each scaling technique is preferred and why.

1. Standard Scaling

Used when the data needs to have mean = 0 and standard deviation = 1.

Preferred for algorithms such as Logistic Regression, Support Vector Machine (SVM), Linear Regression, and PCA.

Suitable when features have different ranges, because it standardizes them to a similar scale.

Works better when the data follows a normal (Gaussian) distribution.

Handles outliers better than Min-Max scaling because it uses mean and standard deviation instead of minimum and maximum values.

2.Min-Max Scaling

Used to normalize data into a fixed range between 0 and 1.

Preferred for distance-based algorithms such as KNN and K-Means clustering.

Commonly used in Neural Networks and Deep Learning models where normalized inputs improve performance.

Useful when the exact range of data needs to be preserved.

Works best when the dataset does not contain many outliers, because extreme values can affect the scaling.

3.Robust Scaling

When the dataset contains many outliers.

When extreme values distort the mean and standard deviation.

When features have very large ranges with unusual values.

Useful in real-world datasets where data is not normally distributed.

Preferred when Standard Scaling and Min-Max Scaling are affected by outliers.

# 2. Encoding Techniques:

●	Apply One-Hot Encoding to categorical variables with less than 5 categories.

In [5]:
# Identify categorical columns
cat_cols = df.select_dtypes(include='object').columns

# Select columns with less than 5 categories
small_cat_cols = [col for col in cat_cols if df[col].nunique() < 5]

# Apply One-Hot Encoding
df_encoded = pd.get_dummies(df, columns=small_cat_cols)

# Display dataset
df_encoded.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,capital_gain,capital_loss,hours_per_week,native_country,sex_ Female,sex_ Male,income_ <=50K,income_ >50K
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,2174,0,40,United-States,False,True,True,False
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,0,0,13,United-States,False,True,True,False
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,0,0,40,United-States,False,True,True,False
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,0,0,40,United-States,False,True,True,False
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,0,0,40,Cuba,True,False,True,False

●	Use Label Encoding for categorical variables. Data Exploration and Preprocessing:

In [6]:
categorical_columns = df.select_dtypes(include='object').columns
print(categorical_columns)

Index(['workclass', 'education', 'marital_status', 'occupation',
       'relationship', 'race', 'sex', 'native_country', 'income'],
      dtype='object')

In [7]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

for col in categorical_columns:
    df[col] = le.fit_transform(df[col])

In [8]:
df.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,39,7,77516,9,13,4,1,1,4,1,2174,0,40,39,0
1,50,6,83311,9,13,2,4,0,4,1,0,0,13,39,0
2,38,4,215646,11,9,0,6,1,4,1,0,0,40,39,0
3,53,4,234721,1,7,2,6,0,2,1,0,0,40,39,0
4,28,4,338409,9,13,2,10,5,2,0,0,0,40,5,0

●	Load the dataset and conduct basic data exploration (summary statistics, missing values, data types).

In [10]:
import pandas as pd
df = pd.read_csv("adult_with_headers (1).csv")
df.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [11]:
df.shape

(32561, 15)

In [12]:
df.dtypes

age                int64
workclass         object
fnlwgt             int64
education         object
education_num      int64
marital_status    object
occupation        object
relationship      object
race              object
sex               object
capital_gain       int64
capital_loss       int64
hours_per_week     int64
native_country    object
income            object
dtype: object

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  int64
 1   workclass       32561 non-null  object
 2   fnlwgt          32561 non-null  int64
 3   education       32561 non-null  object
 4   education_num   32561 non-null  int64
 5   marital_status  32561 non-null  object
 6   occupation      32561 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital_gain    32561 non-null  int64
 11  capital_loss    32561 non-null  int64
 12  hours_per_week  32561 non-null  int64
 13  native_country  32561 non-null  object
 14  income          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB

In [14]:
df.describe()

,age,fnlwgt,education_num,capital_gain,capital_loss,hours_per_week
count,32561.000000,3.256100e+04,32561.000000,32561.000000,32561.000000,32561.000000
mean,38.581647,1.897784e+05,10.080679,1077.648844,87.303830,40.437456
std,13.640433,1.055500e+05,2.572720,7385.292085,402.960219,12.347429
min,17.000000,1.228500e+04,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.178270e+05,9.000000,0.000000,0.000000,40.000000
50%,37.000000,1.783560e+05,10.000000,0.000000,0.000000,40.000000
75%,48.000000,2.370510e+05,12.000000,0.000000,0.000000,45.000000
max,90.000000,1.484705e+06,16.000000,99999.000000,4356.000000,99.000000

In [15]:
df.isnull().sum()

age               0
workclass         0
fnlwgt            0
education         0
education_num     0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
income            0
dtype: int64

●	les with more than 5 categories.

In [17]:
categorical_cols = df.select_dtypes(include='object').columns
large_category_cols = [col for col in categorical_cols if df[col].nunique() > 5]

print(large_category_cols)

['workclass', 'education', 'marital_status', 'occupation', 'relationship', 'native_country']

In [18]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

for col in large_category_cols:
    df[col] = le.fit_transform(df[col])

In [19]:
df.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,39,7,77516,9,13,4,1,1,White,Male,2174,0,40,39,<=50K
1,50,6,83311,9,13,2,4,0,White,Male,0,0,13,39,<=50K
2,38,4,215646,11,9,0,6,1,White,Male,0,0,40,39,<=50K
3,53,4,234721,1,7,2,6,0,Black,Male,0,0,40,39,<=50K
4,28,4,338409,9,13,2,10,5,Black,Female,0,0,40,5,<=50K

●	Discuss the pros and cons of One-Hot Encoding and Label Encoding

A. Pros of One-Hot Encoding

1.Does not assume any order between categories

2.Works well with nominal categorical data

3.Prevents the model from misunderstanding relationships between categories

4.Suitable for variables with few categories

A. Cons of One-Hot Encoding

1.Creates many new columns if categories are large

2.Increases dataset size and memory usage

3.Can lead to high dimensionality

B.Pros of Label Encoding

1.Simple and fast to implement

2.Reduces memory usage

3.Suitable for variables with many categories

B.Cons of Label Encoding

1.Creates false order/relationship between categories

2.Machine learning models may think one category is greater than another

# 3. Feature Engineering

●	Create at least 2 new features that could be beneficial for the model. Explain the rationale behind your choices.

In [23]:

# Remove extra spaces in column names
df.columns = df.columns.str.strip()

# Replace spaces with underscore (optional but recommended)
df.columns = df.columns.str.replace(" ", "_")

# Check column names
print(df.columns)

# Feature 1: Work Intensity
df["work_intensity"] = df["hours_per_week"] / df["age"]

# Feature 2: Capital Gain Ratio
df["capital_ratio"] = df["capital_gain"] / (df["capital_loss"] + 1)

# View new features
df[["work_intensity","capital_ratio"]].head()

Index(['age', 'workclass', 'fnlwgt', 'education', 'education_num',
       'marital_status', 'occupation', 'relationship', 'race', 'sex',
       'capital_gain', 'capital_loss', 'hours_per_week', 'native_country',
       'income', 'work_intensity', 'capital_ratio'],
      dtype='object')

   work_intensity  capital_ratio
0        1.025641         2174.0
1        0.260000            0.0
2        1.052632            0.0
3        0.754717            0.0
4        1.428571            0.0

●	Apply a transformation (e.g., log transformation) to at least one skewed numerical feature and justify your choice.

In [24]:
import numpy as np

# Apply log transformation
df["capital_gain_log"] = np.log1p(df["capital_gain"])

# View transformed feature
df[["capital_gain", "capital_gain_log"]].head()

   capital_gain  capital_gain_log
0          2174          7.684784
1             0          0.000000
2             0          0.000000
3             0          0.000000
4             0          0.000000